# Generated by Django 5.2.9 on 2026-07-02 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0003_alter_coursestructure_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='course_management.coursestructure')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_verification',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'verifier'), name='unique_course_verifier_verification')],
            },
        ),
    ]
