# Generated by Django 5.2.4 on 2025-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_code', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('prog_type', models.CharField(blank=True, max_length=5, null=True)),
                ('sem', models.CharField(blank=True, max_length=10, null=True)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('part', models.CharField(blank=True, max_length=10, null=True)),
                ('course_category', models.CharField(blank=True, max_length=20, null=True)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('hrs_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('marks_cia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marks_ese', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Structure',
                'verbose_name_plural': 'Course Structures',
                'db_table': 'course_str',
                'ordering': ['-created_at'],
            },
        ),
    ]
