# Generated by Django 5.2.9 on 2026-02-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestr',
            name='pass_marks',
        ),
    ]
