# Generated by Django 5.2.9 on 2026-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0002_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/'),
        ),
    ]
