# Generated by Django 5.2.9 on 2026-02-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0002_remove_coursestr_pass_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestr',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
