# Generated by Django 5.2.9 on 2026-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0003_coursecontent_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestr',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursestr',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
