# Generated by Django 5.2.9 on 2026-04-30

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0003_alter_coursestr_branch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursestr',
            constraint=models.UniqueConstraint(
                condition=Q(('course_code__isnull', False), ~Q(('course_code', ''))),
                fields=('course_code',),
                name='unique_non_blank_course_code',
            ),
        ),
    ]
