# Generated by Django 5.2.9 on 2026-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0004_coursestr_is_finalized_coursestr_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/'),
        ),
    ]
