# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_center", "0004_add_unique_course_code_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestr",
            name="degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
