# Generated by Django 6.0.4 on 2026-06-04 05:14

import modules.upload_center.models
import modules.upload_center.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0005_coursestr_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=modules.upload_center.storage.OverwriteStorage(), upload_to=modules.upload_center.models.course_pdf_upload_path),
        ),
    ]
