# Generated by Django 5.2.9 on 2026-02-12 04:41

import modules.upload_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_center', '0006_alter_coursecontent_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=modules.upload_center.models.course_pdf_upload_path),
        ),
    ]
