# Generated by Django 6.0.2 on 2026-06-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='course_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_syllabus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('sem', models.CharField(blank=True, max_length=10, null=True)),
                ('course_category', models.CharField(blank=True, max_length=20, null=True)),
                ('part', models.CharField(blank=True, max_length=10, null=True)),
                ('hrs_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('marks_cia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marks_ese', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='program_manage.program')),
            ],
            options={
                'db_table': 'course_structure',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('program', 'course_code'), name='unique_program_course')],
            },
        ),
    ]
