# Generated by Django 5.2.9 on 2026-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestructure',
            name='course_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
