# Generated by Django 5.2.9 on 2026-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=20)),
                ('prog_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=5)),
                ('prog_category', models.CharField(choices=[('Aided', 'Aided'), ('SFM', 'SFM'), ('SFW', 'SFW')], max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'program_master',
                'unique_together': {('year', 'prog_type', 'prog_category', 'branch', 'semester')},
            },
        ),
    ]
