# Generated by Django 6.0.2 on 2026-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_code', models.CharField(max_length=20, unique=True)),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('prog_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=5)),
                ('prog_category', models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program_master',
                'ordering': ['prog_code'],
            },
        ),
    ]
