# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_manage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="year",
            new_name="degree",
        ),
        migrations.AlterField(
            model_name="program",
            name="degree",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("prog_type", "prog_category", "degree", "branch", "prog_code")},
        ),
    ]
