# Generated by Django 5.2.9 on 2026-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='prog_category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science'), ('UG', 'UG'), ('PG', 'PG')], max_length=10),
        ),
    ]
