# Generated by Codex on 2026-05-12

from django.db import migrations


def clear_existing_degree_values(apps, schema_editor):
    Program = apps.get_model("program_manage", "Program")
    Program.objects.all().update(degree="")


class Migration(migrations.Migration):

    dependencies = [
        ("program_manage", "0002_rename_year_to_degree"),
    ]

    operations = [
        migrations.RunPython(clear_existing_degree_values, migrations.RunPython.noop),
    ]
